### ISSUE TITLE
Write stored procedures

### ISSUE THREAD

**Issue by amenders** [Renascentinc/retina-api#4]
Need to finish writing up stored procedures
- [x] search
- [x] transfer
- [x] search by retina ID and serial number
- [x] transfer by retina ID and serial number
- [x] update tool with user
- [x] update tool with status
- [x] transfer user dropdown
- [x] for the transfer search proc, if currentUser = shop manager, call normal search proc
- [x] Up for discussion: to reduce load time, should the search proc only return those values that the search page needs to show?

**Comment by JerebChase** [comment]
All stored procedures have been written for the above issues.
