### ISSUE TITLE
GET /tools/:id does not return all needed info

### ISSUE THREAD

**Issue by Jbcampbe** [Renascentinc/retina-api#5]
Receiving responses back from the api with the following structure. Need to add an owner (I think this may be covered by Jere's DB refactor but just filing just in case.
```
{
 "data": { 
   "type": "tool",
   "id": 222222,
   "attributes": { 
     "toolclass": "Standard", 
     "type": "Black Hole Generator",
     "brand": "Black and Decker", 
     "datepurchased": "1899-12-30T00:00:00",
     "purchasedfrom": "Nowhere", 
     "price": 10000.1200, 
     "modelnumber": "JJQ",
     "status":"Stolen"
   }
 }
}
```

**Comment by JerebChase** [comment]
UserID and UserName have been added, I need to include Email and Phone number in my proc as well. I'll get on that today.

**Comment by JerebChase** [comment]
Added necessary info to tool_details proc.
