### ISSUE TITLE
Enforce business rules for "deleted" items

### ISSUE THREAD

**Issue by ekraihan** [Renascentinc/retina-api#70]
Tools and Users can have statuses of "OUT_OF_SERVICE" and "INACTIVE", respectively. These tools should never show up on the front end so we need to not return, search, (transfer?), etc. these entities. Procs that might need this:

- search_tool_xxx
- get_all_tool
- get_all_user
- search_user
- transfer_tool
- update_tool?
- update_user?

I may also be able to check Jeremy's sprocs in retina-api v2 for ideas

**Comment by amenders** [comment]
This brings up an interesting point. If we are treating the “out of service” status as basically the same as “deleted,” then I think that we shouldn’t allow simple status changes to OOS, but rather provide a separate “delete” button. Or we could have a separate active/inactive field on a tool for deleted ones, and keep OOS as an actual tool status that can be transferred into and out of.

-Amos Endersen
